### PR TITLE
chore: webapp routing rewrite

### PR DESCRIPTION
**Pull request by jjgancfer**
Just a minor PR to replace the JSON-based routing for a declarative one.

### CODE REVIEW

**Review by UO283615 — DISMISSED** [review]

**Comment by Toto-hitori** [comment]
Does this PR need to be to master? Or should it be to develop? (asking for real, I have no idea)

**Comment by UO283615** [comment]
I did not notice that this was going into master, if it should go into master I think it should also go into develop as well right?

**Comment by jjgancfer** [comment]
> Does this PR need to be to master? Or should it be to develop? (asking for real, I have no idea)

> I did not notice that this was going into master, if it should go into master I think it should also go into develop as well right?

I thought I had chosen `develop`. It his now fixed.

**Review by Toto-hitori — APPROVED** [review]

**Review by gony02 — APPROVED** [review]
Everything seems OK.

**Pull request merged**
